<a href="https://colab.research.google.com/github/TurgutOzkan/Time_Series_Analysis/blob/master/Time_Series_1_Data_Management.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I will examine the implementation of time series analysis using Python in a series of posts.Â In this post, we will work on how to get our data ready for time series analysis. Time series are very important especially analyzing financial data, sensor input, or basically, any signal that extends over time. I will include codes and a brief explanation. They are pretty straightforward.

In [0]:
import numpy as np
import pandas as pd
from datetime import datetime

Timestamp and period are important tools to play with time series. The latter contains frequency attribute, which is very helpful in modifying the scope of your data.

In [0]:
time=pd.Timestamp(datetime(2018,12,23))
print(time)
print(time.year)
print(time.day)
print(time.weekday_name)

2018-12-23 00:00:00
2018
23
Sunday

In [0]:
period = pd.Period("2018-12") # monthly period
print(period)
print(period.asfreq("D")) #daily frequency
print(period.asfreq("H")) # hourly frequency

2018-12
2018-12-31
2018-12-31 23:00

In [0]:
time=period.to_timestamp() # Automatically adds the first day of the month and hour as 00:00
print(time)
time.to_period("D") # converts a time stamp

2018-12-01 00:00:00

Period('2018-12-01', 'D')

**Converting a series to datetime format.**

In [0]:
#Let's say we want to convert a column to datetime.
z=pd.date_range(start="12-01-2018", periods=10, freq="D") # Create random data for the time series. It is integers
DF=pd.DataFrame(data= z, columns=["X1"])
DF.X1=pd.to_datetime(DF.X1)

**Creating Time Series**

In [0]:
date_time_index=pd.date_range(start="12-01-2018", periods=100, freq="D") # creates a date-time index object
data = np.random.randn(100,2) # Create random data for the time series
DF=pd.DataFrame(data= data, index= date_time_index, columns=["X1", "X2"]) # converts to a dataframe using the date-time index 
DF.head()

                  X1        X2
2018-12-01  0.624325 -0.495021
2018-12-02 -0.099198 -0.339282
2018-12-03 -0.382629  2.048525
2018-12-04 -0.023323  0.563259
2018-12-05 -1.219090  0.528440

**Slicing the data**

In [0]:
DF.X1["2018-12-01":"2018-12-03"]

2018-12-01    0.624325
2018-12-02   -0.099198
2018-12-03   -0.382629
Freq: D, Name: X1, dtype: float64

**Changing the frequency of the series**

In [0]:
DF.asfreq('W')

                  X1        X2
2018-12-02 -0.099198 -0.339282
2018-12-09 -0.823008 -0.240675
2018-12-16 -0.296962 -0.318172
2018-12-23  1.898519 -0.261032
2018-12-30  0.097803 -0.502945
2019-01-06 -0.095242  2.477480
2019-01-13  0.666292 -0.286388
2019-01-20 -0.400630 -0.156985
2019-01-27  1.089333 -0.872086
2019-02-03  1.309500 -3.205892
2019-02-10 -0.000840 -0.787559
2019-02-17 -1.823047  0.758552
2019-02-24  0.581872 -1.451475
2019-03-03 -0.353188 -0.001957
2019-03-10  0.689396  0.976791

In [0]:
DF.resample("W") #creates a resampler object

DatetimeIndexResampler [freq=<Week: weekday=6>, axis=0, closed=right, label=right, convention=start, base=0]

In [0]:
DF.X1.resample("W").asfreq() # if you apply another method, you get resampled dataframe

2018-12-02   -0.099198
2018-12-09   -0.823008
2018-12-16   -0.296962
2018-12-23    1.898519
2018-12-30    0.097803
2019-01-06   -0.095242
2019-01-13    0.666292
2019-01-20   -0.400630
2019-01-27    1.089333
2019-02-03    1.309500
2019-02-10   -0.000840
2019-02-17   -1.823047
2019-02-24    0.581872
2019-03-03   -0.353188
2019-03-10    0.689396
Freq: W-SUN, Name: X1, dtype: float64

In [0]:
DF.X1.resample("W").mean() # apply another method, you get resampled dataframe, but this time with mean values of X1 per week.

2018-12-02    0.262564
2018-12-09   -0.849346
2018-12-16    0.537632
2018-12-23   -0.036444
2018-12-30   -0.046397
2019-01-06   -0.133059
2019-01-13   -0.165135
2019-01-20   -0.639178
2019-01-27    0.138853
2019-02-03   -0.177281
2019-02-10    0.130841
2019-02-17   -0.270166
2019-02-24    0.308541
2019-03-03    0.285273
2019-03-10    0.659949
Freq: W-SUN, Name: X1, dtype: float64

**Creating Lagged Values**

In [0]:
DF["Lagged_X1"]=DF.X1.shift() # default prediod is 1
DF

                  X1        X2  Lagged_X1
2018-12-01  0.624325 -0.495021        NaN
2018-12-02 -0.099198 -0.339282   0.624325
2018-12-03 -0.382629  2.048525  -0.099198
2018-12-04 -0.023323  0.563259  -0.382629
2018-12-05 -1.219090  0.528440  -0.023323
2018-12-06 -0.577899 -1.128838  -1.219090
2018-12-07 -1.938390 -0.932730  -0.577899
2018-12-08 -0.981086 -0.891412  -1.938390
2018-12-09 -0.823008 -0.240675  -0.981086
2018-12-10  0.033392 -1.169605  -0.823008
2018-12-11  1.888944 -0.300988   0.033392
2018-12-12  0.403493  1.603189   1.888944
2018-12-13  0.088324  2.222421   0.403493
2018-12-14  0.455906  0.155119   0.088324
2018-12-15  1.190325  0.605482   0.455906
2018-12-16 -0.296962 -0.318172   1.190325
2018-12-17 -0.240205  0.281918  -0.296962
2018-12-18  0.177500 -1.480880  -0.240205
2018-12-19 -1.588182  0.683381   0.177500
2018-12-20  0.280514  0.271680  -1.588182
2018-12-21 -0.014295 -1.037618   0.280514
2018-12-22 -0.768962 -1.602175  -0.014295
2018-12-23  1.898519 -0.261032  -0.768962
2018-12-24  0.210881 -0.284506   1.898519
2018-12-25 -0.488548 -1.340615   0.210881
2018-12-26 -2.108726  0.026857  -0.488548
2018-12-27 -0.703119 -1.609688  -2.108726
2018-12-28  2.552578  0.738777  -0.703119
2018-12-29  0.114348  0.292359   2.552578
2018-12-30  0.097803 -0.502945   0.114348
...              ...       ...        ...
2019-02-09  0.288844  0.121933   0.496633
2019-02-10 -0.000840 -0.787559   0.288844
2019-02-11  0.093083  0.693623  -0.000840
2019-02-12  0.761831 -0.363789   0.093083
2019-02-13 -1.175789  1.491262   0.761831
2019-02-14  0.165798 -0.965803  -1.175789
2019-02-15 -0.684094 -1.042531   0.165798
2019-02-16  0.771055 -1.819032  -0.684094
2019-02-17 -1.823047  0.758552   0.771055
2019-02-18  1.301716 -0.613849  -1.823047
2019-02-19  0.522749 -0.094771   1.301716
2019-02-20 -0.261774 -1.149796   0.522749
2019-02-21  0.372518 -0.305784  -0.261774
2019-02-22 -0.512443 -0.521635   0.372518
2019-02-23  0.155149 -0.339048  -0.512443
2019-02-24  0.581872 -1.451475   0.155149
2019-02-25  0.843998  0.733624   0.581872
2019-02-26  0.871545  1.127246   0.843998
2019-02-27 -0.878413  1.122862   0.871545
2019-02-28  0.207302 -1.156366  -0.878413
2019-03-01  0.706263  1.394555   0.207302
2019-03-02  0.599403  0.470085   0.706263
2019-03-03 -0.353188 -0.001957   0.599403
2019-03-04  0.286273  0.657048  -0.353188
2019-03-05  0.110075  1.747720   0.286273
2019-03-06 -0.275972 -0.063809   0.110075
2019-03-07  1.334505  1.437497  -0.275972
2019-03-08  1.568144 -0.319622   1.334505
2019-03-09  0.907225 -1.073458   1.568144
2019-03-10  0.689396  0.976791   0.907225

[100 rows x 3 columns]

In [0]:
DF["Future_Shifted_X1"]=DF.X1.shift(periods = -1) # default prediod is 1
DF

                  X1        X2  Lagged_X1  Future_Shifted_X1
2018-12-01  0.624325 -0.495021        NaN          -0.099198
2018-12-02 -0.099198 -0.339282   0.624325          -0.382629
2018-12-03 -0.382629  2.048525  -0.099198          -0.023323
2018-12-04 -0.023323  0.563259  -0.382629          -1.219090
2018-12-05 -1.219090  0.528440  -0.023323          -0.577899
2018-12-06 -0.577899 -1.128838  -1.219090          -1.938390
2018-12-07 -1.938390 -0.932730  -0.577899          -0.981086
2018-12-08 -0.981086 -0.891412  -1.938390          -0.823008
2018-12-09 -0.823008 -0.240675  -0.981086           0.033392
2018-12-10  0.033392 -1.169605  -0.823008           1.888944
2018-12-11  1.888944 -0.300988   0.033392           0.403493
2018-12-12  0.403493  1.603189   1.888944           0.088324
2018-12-13  0.088324  2.222421   0.403493           0.455906
2018-12-14  0.455906  0.155119   0.088324           1.190325
2018-12-15  1.190325  0.605482   0.455906          -0.296962
2018-12-16 -0.296962 -0.318172   1.190325          -0.240205
2018-12-17 -0.240205  0.281918  -0.296962           0.177500
2018-12-18  0.177500 -1.480880  -0.240205          -1.588182
2018-12-19 -1.588182  0.683381   0.177500           0.280514
2018-12-20  0.280514  0.271680  -1.588182          -0.014295
2018-12-21 -0.014295 -1.037618   0.280514          -0.768962
2018-12-22 -0.768962 -1.602175  -0.014295           1.898519
2018-12-23  1.898519 -0.261032  -0.768962           0.210881
2018-12-24  0.210881 -0.284506   1.898519          -0.488548
2018-12-25 -0.488548 -1.340615   0.210881          -2.108726
2018-12-26 -2.108726  0.026857  -0.488548          -0.703119
2018-12-27 -0.703119 -1.609688  -2.108726           2.552578
2018-12-28  2.552578  0.738777  -0.703119           0.114348
2018-12-29  0.114348  0.292359   2.552578           0.097803
2018-12-30  0.097803 -0.502945   0.114348          -1.056253
...              ...       ...        ...                ...
2019-02-09  0.288844  0.121933   0.496633          -0.000840
2019-02-10 -0.000840 -0.787559   0.288844           0.093083
2019-02-11  0.093083  0.693623  -0.000840           0.761831
2019-02-12  0.761831 -0.363789   0.093083          -1.175789
2019-02-13 -1.175789  1.491262   0.761831           0.165798
2019-02-14  0.165798 -0.965803  -1.175789          -0.684094
2019-02-15 -0.684094 -1.042531   0.165798           0.771055
2019-02-16  0.771055 -1.819032  -0.684094          -1.823047
2019-02-17 -1.823047  0.758552   0.771055           1.301716
2019-02-18  1.301716 -0.613849  -1.823047           0.522749
2019-02-19  0.522749 -0.094771   1.301716          -0.261774
2019-02-20 -0.261774 -1.149796   0.522749           0.372518
2019-02-21  0.372518 -0.305784  -0.261774          -0.512443
2019-02-22 -0.512443 -0.521635   0.372518           0.155149
2019-02-23  0.155149 -0.339048  -0.512443           0.581872
2019-02-24  0.581872 -1.451475   0.155149           0.843998
2019-02-25  0.843998  0.733624   0.581872           0.871545
2019-02-26  0.871545  1.127246   0.843998          -0.878413
2019-02-27 -0.878413  1.122862   0.871545           0.207302
2019-02-28  0.207302 -1.156366  -0.878413           0.706263
2019-03-01  0.706263  1.394555   0.207302           0.599403
2019-03-02  0.599403  0.470085   0.706263          -0.353188
2019-03-03 -0.353188 -0.001957   0.599403           0.286273
2019-03-04  0.286273  0.657048  -0.353188           0.110075
2019-03-05  0.110075  1.747720   0.286273          -0.275972
2019-03-06 -0.275972 -0.063809   0.110075           1.334505
2019-03-07  1.334505  1.437497  -0.275972           1.568144
2019-03-08  1.568144 -0.319622   1.334505           0.907225
2019-03-09  0.907225 -1.073458   1.568144           0.689396
2019-03-10  0.689396  0.976791   0.907225                NaN

[100 rows x 4 columns]

**Calculating Differences Easily**

In [0]:
DF["X3"] = DF.X1.div(5).mul(10) # You can use divide and multiply methods for data frame columns
DF["X3"] = DF["X3"] +5
DF["X3"] = DF["X3"].apply(lambda x: round(x, 0)) # rounding the column so later operations become clearer
DF.head()

                  X1        X2  Lagged_X1  Future_Shifted_X1   X3
2018-12-01  0.624325 -0.495021        NaN          -0.099198  6.0
2018-12-02 -0.099198 -0.339282   0.624325          -0.382629  5.0
2018-12-03 -0.382629  2.048525  -0.099198          -0.023323  4.0
2018-12-04 -0.023323  0.563259  -0.382629          -1.219090  5.0
2018-12-05 -1.219090  0.528440  -0.023323          -0.577899  3.0

In [0]:
DF["DIFF_X3"]=DF.X3.diff()  # difference between time t and time t-1. It looks differences in rows sequentially for a given column.
DF.head()

                  X1        X2  Lagged_X1  Future_Shifted_X1   X3  DIFF_X3
2018-12-01  0.624325 -0.495021        NaN          -0.099198  6.0      NaN
2018-12-02 -0.099198 -0.339282   0.624325          -0.382629  5.0     -1.0
2018-12-03 -0.382629  2.048525  -0.099198          -0.023323  4.0     -1.0
2018-12-04 -0.023323  0.563259  -0.382629          -1.219090  5.0      1.0
2018-12-05 -1.219090  0.528440  -0.023323          -0.577899  3.0     -2.0

In [0]:
DF["PERCENT_X3"]=DF.X3.pct_change().mul(100)  # similar to diff, pct_change() provides percentage changes for adjacent rows.
# If you provide a value, you can find further time differences, for example, change between now and seventh value.
DF.head()

,X1,X2,Lagged_X1,Future_Shifted_X1,X3,DIFF_X3,PERCENT_X3
2018-12-01,0.624325,-0.495021,NaN,-0.099198,6.0,NaN,NaN
2018-12-02,-0.099198,-0.339282,0.624325,-0.382629,5.0,-1.0,-16.666667
2018-12-03,-0.382629,2.048525,-0.099198,-0.023323,4.0,-1.0,-20.000000
2018-12-04,-0.023323,0.563259,-0.382629,-1.219090,5.0,1.0,25.000000
2018-12-05,-1.219090,0.528440,-0.023323,-0.577899,3.0,-2.0,-40.000000

**Window Functions**

Moving averages are useful for a number of purposes such as smoothing out short-term fluctuations, removing outliers or emphasizing long-term trends.

**(1) Rolling Averages For Time Series**

In [0]:
DF.rolling(window='2D').mean() # every data points are the average of preceding two days.

,X1,X2,Lagged_X1,Future_Shifted_X1,X3,DIFF_X3,PERCENT_X3
2018-12-01,0.624325,-0.495021,NaN,-0.099198,6.0,NaN,NaN
2018-12-02,0.262564,-0.417152,0.624325,-0.240913,5.5,-1.0,-16.666667
2018-12-03,-0.240913,0.854621,0.262564,-0.202976,4.5,-1.0,-18.333333
2018-12-04,-0.202976,1.305892,-0.240913,-0.621207,4.5,0.0,2.500000
2018-12-05,-0.621207,0.545850,-0.202976,-0.898495,4.0,-0.5,-7.500000
2018-12-06,-0.898495,-0.300199,-0.621207,-1.258144,3.5,-0.5,-3.333333
2018-12-07,-1.258144,-1.030784,-0.898495,-1.459738,2.5,-1.0,-20.833333
2018-12-08,-1.459738,-0.912071,-1.258144,-0.902047,2.0,-0.5,62.500000
2018-12-09,-0.902047,-0.566043,-1.459738,-0.394808,3.0,1.0,100.000000
2018-12-10,-0.394808,-0.705140,-0.902047,0.961168,4.0,1.0,33.333333
2018-12-11,0.961168,-0.735296,-0.394808,1.146219,7.0,3.0,73.333333
2018-12-12,1.146219,0.651100,0.961168,0.245908,7.5,0.5,23.333333
2018-12-13,0.245908,1.912805,1.146219,0.272115,5.5,-2.0,-25.000000
2018-12-14,0.272115,1.188770,0.245908,0.823116,5.5,0.0,1.666667
2018-12-15,0.823116,0.380300,0.272115,0.446681,6.5,1.0,18.333333
2018-12-16,0.446681,0.143655,0.823116,-0.268584,5.5,-1.0,-13.095238
2018-12-17,-0.268584,-0.018127,0.446681,-0.031353,4.5,-1.0,-8.928571
2018-12-18,-0.031353,-0.599481,-0.268584,-0.705341,5.0,0.5,12.500000
2018-12-19,-0.705341,-0.398750,-0.031353,-0.653834,3.5,-1.5,-30.000000
2018-12-20,-0.653834,0.477530,-0.705341,0.133110,4.0,0.5,70.000000
2018-12-21,0.133110,-0.382969,-0.653834,-0.391629,5.5,1.5,91.666667
2018-12-22,-0.391629,-1.319896,0.133110,0.564778,4.0,-1.5,-28.333333
2018-12-23,0.564778,-0.931603,-0.391629,1.054700,6.0,2.0,80.000000
2018-12-24,1.054700,-0.272769,0.564778,-0.138834,7.0,1.0,77.777778
2018-12-25,-0.138834,-0.812560,1.054700,-1.298637,4.5,-2.5,-32.222222
2018-12-26,-1.298637,-0.656879,-0.138834,-1.405922,2.5,-2.0,-47.500000
2018-12-27,-1.405922,-0.791416,-1.298637,0.924730,2.5,0.0,112.500000
2018-12-28,0.924730,-0.435456,-1.405922,1.333463,7.0,4.5,225.000000
2018-12-29,1.333463,0.515568,0.924730,0.106076,7.5,0.5,50.000000
2018-12-30,0.106076,-0.105293,1.333463,-0.479225,5.0,-2.5,-25.000000
...,...,...,...,...,...,...,...
2019-02-09,0.392739,0.058246,0.343881,0.144002,6.0,0.5,10.000000
2019-02-10,0.144002,-0.332813,0.392739,0.046121,5.5,-0.5,-8.333333
2019-02-11,0.046121,-0.046968,0.144002,0.427457,5.0,-0.5,-8.333333
2019-02-12,0.427457,0.164917,0.046121,-0.206979,6.0,1.0,20.000000
2019-02-13,-0.206979,0.563736,0.427457,-0.504995,5.0,-1.0,-8.571429
2019-02-14,-0.504995,0.262729,-0.206979,-0.259148,4.0,-1.0,4.761905
2019-02-15,-0.259148,-1.004167,-0.504995,0.043480,4.5,0.5,23.333333
2019-02-16,0.043480,-1.430781,-0.259148,-0.525996,5.5,1.0,27.500000
2019-02-17,-0.525996,-0.530240,0.043480,-0.260666,4.0,-1.5,-5.357143
2019-02-18,-0.260666,0.072351,-0.525996,0.912232,4.5,0.5,307.142857
2019-02-19,0.912232,-0.354310,-0.260666,0.130488,7.0,2.5,337.500000
2019-02-20,0.130488,-0.622284,0.912232,0.055372,5.0,-2.0,-29.166667
2019-02-21,0.055372,-0.727790,0.130488,-0.069963,5.0,0.0,8.333333
2019-02-22,-0.069963,-0.413709,0.055372,-0.178647,5.0,0.0,8.333333
2019-02-23,-0.178647,-0.430341,-0.069963,0.368511,4.5,-0.5,-4.166667
2019-02-24,0.368511,-0.895261,-0.178647,0.712935,5.5,1.0,22.500000
2019-02-25,0.712935,-0.358925,0.368511,0.857772,6.5,1.0,18.333333
2019-02-26,0.857772,0.930435,0.712935,-0.003434,7.0,0.5,8.333333
2019-02-27,-0.003434,1.125054,0.857772,-0.335556,5.0,-2.0,-28.571429
2019-02-28,-0.335556,-0.016752,-0.003434,0.456782,4.0,-1.0,4.761905
2019-03-01,0.456782,0.119095,-0.335556,0.652833,5.5,1.5,43.333333
2019-03-02,0.652833,0.932320,0.456782,0.123108,6.0,0.5,10.000000
2019-03-03,0.123108,0.234064,0.652833,-0.033457,5.0,-1.0,-16.666667
2019-03-04,-0.033457,0.327545,0.123108,0.198174,5.0,0.0,8.333333
2019-03-05,0.198174,1.202384,-0.033457,-0.082949,5.5,0.5,16.666667
2019-03-06,-0.082949,0.841956,0.198174,0.529267,4.5,-1.0,-18.333333
2019-03-07,0.529267,0.686844,-0.082949,1.451325,6.0,1.5,40.000000
2019-03-08,1.451325,0.558938,0.529267,1.237685,8.0,2.0,50.000000
2019-03-09,1.237685,-0.696540,1.451325,0.798310,7.5,-0.5,-6.250000
2019-03-10,0.798310,-0.048334,1.237685,0.689396,6.5,-1.0,-13.392857

**(2) Expanding Window Functions**

In [0]:
DF.X1.expanding().sum().head() # cumulative sum

2018-12-01    0.624325
2018-12-02    0.525127
2018-12-03    0.142499
2018-12-04    0.119175
2018-12-05   -1.099915
Freq: D, Name: X1, dtype: float64

In [0]:
DF.X1.cumsum().head() # a different method for cumulative sum

2018-12-01    0.624325
2018-12-02    0.525127
2018-12-03    0.142499
2018-12-04    0.119175
2018-12-05   -1.099915
Freq: D, Name: X1, dtype: float64

That's it. In a later post, I will discuss various alternatives to analyze time series data using Python. Stay tuned!